steps:


- name: 'gcr.io/$PROJECT_ID/dep'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/glooshot'

- name: 'gcr.io/$PROJECT_ID/go-make'
  entrypoint: 'bash'
  args: ['-c', 'tar -zvcf glooshot-dep.tar.gz ./gopath/pkg/dep']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/glooshot'
  - 'GOPATH=/workspace/gopath'

- name: gcr.io/cloud-builders/gsutil
  args: ['cp', 'glooshot-dep.tar.gz', 'gs://solo-public-cache/glooshot']
