namespace:
  create: false
rbac:
  create: true
crds:
  create: true

glooshot:
  deployment:
    image:
      repository: soloio/glooshot-op
      pullPolicy: Always
      pullSecret: solo-io-docker-secret
    replicas: 1
    prometheusUrl: http://glooshot-prometheus-server/

prometheus:
  enabled: true
  nodeExporter:
    enabled: false

supergloo:
  enabled: true
