apiVersion: glooshot.solo.io/v1
kind: Experiment
metadata:
  name: abort-ratings-metric
  namespace: default
spec:
  spec:
    duration: 600s
    failureConditions:
      - trigger:
          prometheus:
            customQuery: |
              scalar(rate(istio_requests_total{ source_app="productpage",response_code="500",reporter="destination"}[3m]))
            thresholdValue: 0.01
            comparisonOperator: ">"
    faults:
    - destinationServices:
      - name: default-ratings-9080
        namespace: glooshot
      fault:
        abort:
          httpStatus: 500
        percentage: 100
    targetMesh:
      name: istio-istio-system
      namespace: glooshot
