apiVersion: glooshot.solo.io/v1
kind: Experiment
metadata:
  name: abort-ratings-metric-repeat
  namespace: default
spec:
  spec:
    duration: 6000s
    failureConditions:
      - prometheusTrigger:
          customQuery: |
            scalar(sum(istio_requests_total{ source_app="productpage",response_code="500"}))
          thresholdValue: 1000
          comparisonOperator: ">"
    faults:
    - destinationServices:
      - name: default-ratings-9080
        namespace: supergloo-system
      fault:
        abort:
          httpStatus: 500 
        percentage: 100
    targetMesh:
      name: istio
      namespace: supergloo-system
