// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"testing"

	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
)

func TestGlooshotsoloio(t *testing.T) {
	RegisterFailHandler(Fail)
	RunSpecs(t, "Glooshotsoloio Suite")
}
