// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/glooshot/api/v1/glooshot.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/gogo/protobuf/types"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
	v1 "github.com/solo-io/supergloo/pkg/api/v1"
	math "math"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ExperimentResult_State int32

const (
	// Experiment has not started
	ExperimentResult_Pending ExperimentResult_State = 0
	// Experiment started but threshold not met
	ExperimentResult_Started ExperimentResult_State = 1
	// Experiment failed, threshold was exceeded
	ExperimentResult_Failed ExperimentResult_State = 2
	// Experiment succeeded, duration elapsed
	// If duration is not specified, the Experiment will never
	// be marked Succeeded
	ExperimentResult_Succeeded ExperimentResult_State = 3
)

var ExperimentResult_State_name = map[int32]string{
	0: "Pending",
	1: "Started",
	2: "Failed",
	3: "Succeeded",
}

var ExperimentResult_State_value = map[string]int32{
	"Pending":   0,
	"Started":   1,
	"Failed":    2,
	"Succeeded": 3,
}

func (x ExperimentResult_State) String() string {
	return proto.EnumName(ExperimentResult_State_name, int32(x))
}

func (ExperimentResult_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{1, 0}
}

//
//Describes an Experiment that GlooShot should run
type Experiment struct {
	// the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	// indicates whether or not the spec is valid
	// set by glooshot, intended to be read by clients
	Status core.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	// configuration for the Experiment
	Spec *ExperimentSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// the result of the experiment
	Result               ExperimentResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Experiment) Reset()         { *m = Experiment{} }
func (m *Experiment) String() string { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()    {}
func (*Experiment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{0}
}
func (m *Experiment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experiment.Unmarshal(m, b)
}
func (m *Experiment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experiment.Marshal(b, m, deterministic)
}
func (m *Experiment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experiment.Merge(m, src)
}
func (m *Experiment) XXX_Size() int {
	return xxx_messageInfo_Experiment.Size(m)
}
func (m *Experiment) XXX_DiscardUnknown() {
	xxx_messageInfo_Experiment.DiscardUnknown(m)
}

var xxx_messageInfo_Experiment proto.InternalMessageInfo

func (m *Experiment) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Experiment) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Experiment) GetSpec() *ExperimentSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Experiment) GetResult() ExperimentResult {
	if m != nil {
		return m.Result
	}
	return ExperimentResult{}
}

type ExperimentResult struct {
	// the current state of the experiment as reported by glooshot
	State ExperimentResult_State `protobuf:"varint,1,opt,name=state,proto3,enum=glooshot.solo.io.ExperimentResult_State" json:"state,omitempty"`
	// the failure conditions that were met, if the experiment failed
	FailureConditions []*FailureCondition `protobuf:"bytes,2,rep,name=failure_conditions,json=failureConditions,proto3" json:"failure_conditions,omitempty"`
	// time the experiment was started
	TimeStarted time.Time `protobuf:"bytes,3,opt,name=time_started,json=timeStarted,proto3,stdtime" json:"time_started"`
	// the time that elapsed before the experiment completed
	TimeFinished         time.Time `protobuf:"bytes,4,opt,name=time_finished,json=timeFinished,proto3,stdtime" json:"time_finished"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ExperimentResult) Reset()         { *m = ExperimentResult{} }
func (m *ExperimentResult) String() string { return proto.CompactTextString(m) }
func (*ExperimentResult) ProtoMessage()    {}
func (*ExperimentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{1}
}
func (m *ExperimentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentResult.Unmarshal(m, b)
}
func (m *ExperimentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentResult.Marshal(b, m, deterministic)
}
func (m *ExperimentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentResult.Merge(m, src)
}
func (m *ExperimentResult) XXX_Size() int {
	return xxx_messageInfo_ExperimentResult.Size(m)
}
func (m *ExperimentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentResult proto.InternalMessageInfo

func (m *ExperimentResult) GetState() ExperimentResult_State {
	if m != nil {
		return m.State
	}
	return ExperimentResult_Pending
}

func (m *ExperimentResult) GetFailureConditions() []*FailureCondition {
	if m != nil {
		return m.FailureConditions
	}
	return nil
}

func (m *ExperimentResult) GetTimeStarted() time.Time {
	if m != nil {
		return m.TimeStarted
	}
	return time.Time{}
}

func (m *ExperimentResult) GetTimeFinished() time.Time {
	if m != nil {
		return m.TimeFinished
	}
	return time.Time{}
}

type ExperimentSpec struct {
	// the faults this experiment will inject
	// if empty, Glooshit will run a "control" experiment with no faults injected
	Faults []*ExperimentSpec_InjectedFault `protobuf:"bytes,4,rep,name=faults,proto3" json:"faults,omitempty"`
	// conditions on which to stop the experiment and mark it as failed
	// at least one must be specified
	FailureConditions []*FailureCondition `protobuf:"bytes,5,rep,name=failure_conditions,json=failureConditions,proto3" json:"failure_conditions,omitempty"`
	// the duration for which to run the experiment
	// if missing or set to 0 the experiment will run indefinitely
	// only Experiments with a timeout can succeed
	Duration             *time.Duration `protobuf:"bytes,6,opt,name=duration,proto3,stdduration" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ExperimentSpec) Reset()         { *m = ExperimentSpec{} }
func (m *ExperimentSpec) String() string { return proto.CompactTextString(m) }
func (*ExperimentSpec) ProtoMessage()    {}
func (*ExperimentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{2}
}
func (m *ExperimentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentSpec.Unmarshal(m, b)
}
func (m *ExperimentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentSpec.Marshal(b, m, deterministic)
}
func (m *ExperimentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentSpec.Merge(m, src)
}
func (m *ExperimentSpec) XXX_Size() int {
	return xxx_messageInfo_ExperimentSpec.Size(m)
}
func (m *ExperimentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentSpec proto.InternalMessageInfo

func (m *ExperimentSpec) GetFaults() []*ExperimentSpec_InjectedFault {
	if m != nil {
		return m.Faults
	}
	return nil
}

func (m *ExperimentSpec) GetFailureConditions() []*FailureCondition {
	if m != nil {
		return m.FailureConditions
	}
	return nil
}

func (m *ExperimentSpec) GetDuration() *time.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

// decribes a single fault to  inject
type ExperimentSpec_InjectedFault struct {
	// if specified, the fault will only apply to requests sent from these services
	OriginServices []*core.ResourceRef `protobuf:"bytes,1,rep,name=origin_services,json=originServices,proto3" json:"origin_services,omitempty"`
	// if specified, the fault will only apply to requests sent to these services
	DestinationServices []*core.ResourceRef `protobuf:"bytes,2,rep,name=destination_services,json=destinationServices,proto3" json:"destination_services,omitempty"`
	// the type of fault to inject
	Fault                *v1.FaultInjection `protobuf:"bytes,3,opt,name=fault,proto3" json:"fault,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExperimentSpec_InjectedFault) Reset()         { *m = ExperimentSpec_InjectedFault{} }
func (m *ExperimentSpec_InjectedFault) String() string { return proto.CompactTextString(m) }
func (*ExperimentSpec_InjectedFault) ProtoMessage()    {}
func (*ExperimentSpec_InjectedFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{2, 0}
}
func (m *ExperimentSpec_InjectedFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Unmarshal(m, b)
}
func (m *ExperimentSpec_InjectedFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Marshal(b, m, deterministic)
}
func (m *ExperimentSpec_InjectedFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentSpec_InjectedFault.Merge(m, src)
}
func (m *ExperimentSpec_InjectedFault) XXX_Size() int {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Size(m)
}
func (m *ExperimentSpec_InjectedFault) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentSpec_InjectedFault.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentSpec_InjectedFault proto.InternalMessageInfo

func (m *ExperimentSpec_InjectedFault) GetOriginServices() []*core.ResourceRef {
	if m != nil {
		return m.OriginServices
	}
	return nil
}

func (m *ExperimentSpec_InjectedFault) GetDestinationServices() []*core.ResourceRef {
	if m != nil {
		return m.DestinationServices
	}
	return nil
}

func (m *ExperimentSpec_InjectedFault) GetFault() *v1.FaultInjection {
	if m != nil {
		return m.Fault
	}
	return nil
}

// a condition based on an observed prometheus metric
type FailureCondition struct {
	// Types that are valid to be assigned to FailureTrigger:
	//	*FailureCondition_PrometeheusTrigger
	FailureTrigger       isFailureCondition_FailureTrigger `protobuf_oneof:"failure_trigger"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FailureCondition) Reset()         { *m = FailureCondition{} }
func (m *FailureCondition) String() string { return proto.CompactTextString(m) }
func (*FailureCondition) ProtoMessage()    {}
func (*FailureCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{3}
}
func (m *FailureCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailureCondition.Unmarshal(m, b)
}
func (m *FailureCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailureCondition.Marshal(b, m, deterministic)
}
func (m *FailureCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailureCondition.Merge(m, src)
}
func (m *FailureCondition) XXX_Size() int {
	return xxx_messageInfo_FailureCondition.Size(m)
}
func (m *FailureCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_FailureCondition.DiscardUnknown(m)
}

var xxx_messageInfo_FailureCondition proto.InternalMessageInfo

type isFailureCondition_FailureTrigger interface {
	isFailureCondition_FailureTrigger()
	Equal(interface{}) bool
}

type FailureCondition_PrometeheusTrigger struct {
	PrometeheusTrigger *FailureCondition_PrometheusTrigger `protobuf:"bytes,2,opt,name=prometeheus_trigger,json=prometeheusTrigger,proto3,oneof"`
}

func (*FailureCondition_PrometeheusTrigger) isFailureCondition_FailureTrigger() {}

func (m *FailureCondition) GetFailureTrigger() isFailureCondition_FailureTrigger {
	if m != nil {
		return m.FailureTrigger
	}
	return nil
}

func (m *FailureCondition) GetPrometeheusTrigger() *FailureCondition_PrometheusTrigger {
	if x, ok := m.GetFailureTrigger().(*FailureCondition_PrometeheusTrigger); ok {
		return x.PrometeheusTrigger
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FailureCondition) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FailureCondition_OneofMarshaler, _FailureCondition_OneofUnmarshaler, _FailureCondition_OneofSizer, []interface{}{
		(*FailureCondition_PrometeheusTrigger)(nil),
	}
}

func _FailureCondition_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FailureCondition)
	// failure_trigger
	switch x := m.FailureTrigger.(type) {
	case *FailureCondition_PrometeheusTrigger:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PrometeheusTrigger); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FailureCondition.FailureTrigger has unexpected type %T", x)
	}
	return nil
}

func _FailureCondition_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FailureCondition)
	switch tag {
	case 2: // failure_trigger.prometeheus_trigger
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FailureCondition_PrometheusTrigger)
		err := b.DecodeMessage(msg)
		m.FailureTrigger = &FailureCondition_PrometeheusTrigger{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FailureCondition_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FailureCondition)
	// failure_trigger
	switch x := m.FailureTrigger.(type) {
	case *FailureCondition_PrometeheusTrigger:
		s := proto.Size(x.PrometeheusTrigger)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FailureCondition_PrometheusTrigger struct {
	// Types that are valid to be assigned to QueryType:
	//	*FailureCondition_PrometheusTrigger_CustomQuery
	QueryType isFailureCondition_PrometheusTrigger_QueryType `protobuf_oneof:"query_type"`
	// consider the failure condition met if the metric falls below this threshold
	ThresholdValue float64 `protobuf:"fixed64,3,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	// the comparison operator to use when comparing the threshold and observed metric values
	// if the comparison evaluates to true, the failure condition will be considered met
	// possible values are '==', '>', '<', '>=', and '<='
	// defaults to '<'
	ComparisonOperator   string   `protobuf:"bytes,4,opt,name=comparison_operator,json=comparisonOperator,proto3" json:"comparison_operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FailureCondition_PrometheusTrigger) Reset()         { *m = FailureCondition_PrometheusTrigger{} }
func (m *FailureCondition_PrometheusTrigger) String() string { return proto.CompactTextString(m) }
func (*FailureCondition_PrometheusTrigger) ProtoMessage()    {}
func (*FailureCondition_PrometheusTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{3, 0}
}
func (m *FailureCondition_PrometheusTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger.Unmarshal(m, b)
}
func (m *FailureCondition_PrometheusTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger.Marshal(b, m, deterministic)
}
func (m *FailureCondition_PrometheusTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailureCondition_PrometheusTrigger.Merge(m, src)
}
func (m *FailureCondition_PrometheusTrigger) XXX_Size() int {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger.Size(m)
}
func (m *FailureCondition_PrometheusTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_FailureCondition_PrometheusTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_FailureCondition_PrometheusTrigger proto.InternalMessageInfo

type isFailureCondition_PrometheusTrigger_QueryType interface {
	isFailureCondition_PrometheusTrigger_QueryType()
	Equal(interface{}) bool
}

type FailureCondition_PrometheusTrigger_CustomQuery struct {
	CustomQuery string `protobuf:"bytes,1,opt,name=custom_query,json=customQuery,proto3,oneof"`
}

func (*FailureCondition_PrometheusTrigger_CustomQuery) isFailureCondition_PrometheusTrigger_QueryType() {
}

func (m *FailureCondition_PrometheusTrigger) GetQueryType() isFailureCondition_PrometheusTrigger_QueryType {
	if m != nil {
		return m.QueryType
	}
	return nil
}

func (m *FailureCondition_PrometheusTrigger) GetCustomQuery() string {
	if x, ok := m.GetQueryType().(*FailureCondition_PrometheusTrigger_CustomQuery); ok {
		return x.CustomQuery
	}
	return ""
}

func (m *FailureCondition_PrometheusTrigger) GetThresholdValue() float64 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

func (m *FailureCondition_PrometheusTrigger) GetComparisonOperator() string {
	if m != nil {
		return m.ComparisonOperator
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FailureCondition_PrometheusTrigger) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FailureCondition_PrometheusTrigger_OneofMarshaler, _FailureCondition_PrometheusTrigger_OneofUnmarshaler, _FailureCondition_PrometheusTrigger_OneofSizer, []interface{}{
		(*FailureCondition_PrometheusTrigger_CustomQuery)(nil),
	}
}

func _FailureCondition_PrometheusTrigger_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FailureCondition_PrometheusTrigger)
	// query_type
	switch x := m.QueryType.(type) {
	case *FailureCondition_PrometheusTrigger_CustomQuery:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.CustomQuery)
	case nil:
	default:
		return fmt.Errorf("FailureCondition_PrometheusTrigger.QueryType has unexpected type %T", x)
	}
	return nil
}

func _FailureCondition_PrometheusTrigger_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FailureCondition_PrometheusTrigger)
	switch tag {
	case 1: // query_type.custom_query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.QueryType = &FailureCondition_PrometheusTrigger_CustomQuery{x}
		return true, err
	default:
		return false, nil
	}
}

func _FailureCondition_PrometheusTrigger_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FailureCondition_PrometheusTrigger)
	// query_type
	switch x := m.QueryType.(type) {
	case *FailureCondition_PrometheusTrigger_CustomQuery:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CustomQuery)))
		n += len(x.CustomQuery)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FailureCondition_PrometheusTrigger_MeshQuery struct {
	// the name of the metric to monitor
	// possible values:
	// envoy_cluster_upstream_rq
	// istio_requests_total
	// istio_request_duration_seconds_bucket
	Metric string `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	// the service for which the query should be made
	Service              *core.ResourceRef `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *FailureCondition_PrometheusTrigger_MeshQuery) Reset() {
	*m = FailureCondition_PrometheusTrigger_MeshQuery{}
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) String() string {
	return proto.CompactTextString(m)
}
func (*FailureCondition_PrometheusTrigger_MeshQuery) ProtoMessage() {}
func (*FailureCondition_PrometheusTrigger_MeshQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{3, 0, 0}
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery.Unmarshal(m, b)
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery.Marshal(b, m, deterministic)
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery.Merge(m, src)
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) XXX_Size() int {
	return xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery.Size(m)
}
func (m *FailureCondition_PrometheusTrigger_MeshQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery.DiscardUnknown(m)
}

var xxx_messageInfo_FailureCondition_PrometheusTrigger_MeshQuery proto.InternalMessageInfo

func (m *FailureCondition_PrometheusTrigger_MeshQuery) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *FailureCondition_PrometheusTrigger_MeshQuery) GetService() *core.ResourceRef {
	if m != nil {
		return m.Service
	}
	return nil
}

func init() {
	proto.RegisterEnum("glooshot.solo.io.ExperimentResult_State", ExperimentResult_State_name, ExperimentResult_State_value)
	proto.RegisterType((*Experiment)(nil), "glooshot.solo.io.Experiment")
	proto.RegisterType((*ExperimentResult)(nil), "glooshot.solo.io.ExperimentResult")
	proto.RegisterType((*ExperimentSpec)(nil), "glooshot.solo.io.ExperimentSpec")
	proto.RegisterType((*ExperimentSpec_InjectedFault)(nil), "glooshot.solo.io.ExperimentSpec.InjectedFault")
	proto.RegisterType((*FailureCondition)(nil), "glooshot.solo.io.FailureCondition")
	proto.RegisterType((*FailureCondition_PrometheusTrigger)(nil), "glooshot.solo.io.FailureCondition.PrometheusTrigger")
	proto.RegisterType((*FailureCondition_PrometheusTrigger_MeshQuery)(nil), "glooshot.solo.io.FailureCondition.PrometheusTrigger.MeshQuery")
}

func init() {
	proto.RegisterFile("github.com/solo-io/glooshot/api/v1/glooshot.proto", fileDescriptor_b9da8418b9c75752)
}

var fileDescriptor_b9da8418b9c75752 = []byte{
	// 835 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xcf, 0x6f, 0xdc, 0x44,
	0x14, 0xc7, 0xe3, 0xfd, 0xd5, 0xe4, 0x6d, 0x7e, 0x6c, 0x26, 0x51, 0xe5, 0xee, 0xa1, 0x09, 0x8b,
	0x04, 0x3d, 0x14, 0x5b, 0x49, 0x2b, 0x81, 0x00, 0x21, 0xb4, 0x40, 0x08, 0x12, 0x15, 0xad, 0xb7,
	0x42, 0x88, 0x8b, 0xe5, 0xd8, 0x6f, 0xbd, 0x43, 0x6d, 0x8f, 0x99, 0x1f, 0x51, 0x7b, 0xed, 0x15,
	0x09, 0x71, 0xe4, 0x4f, 0xe0, 0x1f, 0x41, 0xe2, 0x6f, 0xe0, 0x00, 0x12, 0xff, 0x41, 0x2f, 0x1c,
	0x38, 0xa1, 0x19, 0x8f, 0x9d, 0xdd, 0x6d, 0xd9, 0x0d, 0xea, 0x29, 0x99, 0x79, 0xdf, 0xcf, 0x7b,
	0x6f, 0xbe, 0xf3, 0x66, 0x0d, 0x27, 0x29, 0x95, 0x33, 0x75, 0xe1, 0xc5, 0x2c, 0xf7, 0x05, 0xcb,
	0xd8, 0x3b, 0x94, 0xf9, 0x69, 0xc6, 0x98, 0x98, 0x31, 0xe9, 0x47, 0x25, 0xf5, 0x2f, 0x4f, 0x9a,
	0xb5, 0x57, 0x72, 0x26, 0x19, 0x19, 0x34, 0x6b, 0x0d, 0x78, 0x94, 0x0d, 0x0f, 0x53, 0x96, 0x32,
	0x13, 0xf4, 0xf5, 0x7f, 0x95, 0x6e, 0x78, 0x3b, 0x65, 0x2c, 0xcd, 0xd0, 0x37, 0xab, 0x0b, 0x35,
	0xf5, 0x13, 0xc5, 0x23, 0x49, 0x59, 0x61, 0xe3, 0x47, 0xcb, 0x71, 0x49, 0x73, 0x14, 0x32, 0xca,
	0x4b, 0x2b, 0xf0, 0x5f, 0xd1, 0x9b, 0xf9, 0xfb, 0x84, 0x36, 0xbd, 0x09, 0x19, 0x49, 0x25, 0x2c,
	0x70, 0x72, 0x0d, 0x20, 0x47, 0x19, 0x25, 0x91, 0x8c, 0x2c, 0x72, 0xf7, 0x1a, 0x08, 0xc7, 0xe9,
	0xff, 0x28, 0x50, 0xaf, 0x57, 0x21, 0xaa, 0x44, 0xae, 0x5d, 0x6c, 0x2a, 0x30, 0x25, 0x69, 0x91,
	0x56, 0xc8, 0xe8, 0xc7, 0x16, 0xc0, 0x67, 0x4f, 0x4b, 0xe4, 0x34, 0xc7, 0x42, 0x92, 0xf7, 0x60,
	0xb3, 0x6e, 0xda, 0x75, 0x8e, 0x9d, 0x3b, 0xfd, 0xd3, 0x9b, 0x5e, 0xcc, 0x38, 0xd6, 0xf6, 0x7b,
	0x0f, 0x6c, 0x74, 0xdc, 0xf9, 0xed, 0x8f, 0xa3, 0x8d, 0xa0, 0x51, 0x93, 0x53, 0xe8, 0x55, 0xfe,
	0xb8, 0x6d, 0xc3, 0x1d, 0x2e, 0x72, 0x13, 0x13, 0xb3, 0x94, 0x55, 0x92, 0xfb, 0xd0, 0x11, 0x25,
	0xc6, 0x6e, 0xcb, 0x10, 0xc7, 0xde, 0xf2, 0x65, 0x7b, 0x57, 0x9d, 0x4d, 0x4a, 0x8c, 0x03, 0xa3,
	0x26, 0x1f, 0x43, 0x8f, 0xa3, 0x50, 0x99, 0x74, 0x3b, 0x86, 0x1b, 0xad, 0xe2, 0x02, 0xa3, 0xac,
	0xeb, 0x56, 0xdc, 0xfb, 0xc3, 0xe7, 0x2f, 0x3a, 0x5d, 0x68, 0xe3, 0xd3, 0xf2, 0xf9, 0x8b, 0xce,
	0x0e, 0xe9, 0x63, 0x23, 0x17, 0xa3, 0xbf, 0x5b, 0x30, 0x58, 0xc6, 0xc9, 0x47, 0xd0, 0xd5, 0x2d,
	0xa3, 0xf1, 0x64, 0xf7, 0xf4, 0xce, 0xfa, 0x8a, 0xe6, 0xc0, 0x18, 0x54, 0x18, 0x79, 0x04, 0x64,
	0x1a, 0xd1, 0x4c, 0x71, 0x0c, 0x63, 0x56, 0x24, 0x54, 0x4f, 0xa6, 0x70, 0x5b, 0xc7, 0xed, 0x57,
	0xb7, 0x7f, 0x56, 0x69, 0x3f, 0xa9, 0xa5, 0xc1, 0xfe, 0x74, 0x69, 0x47, 0x90, 0xcf, 0x61, 0x5b,
	0xcf, 0x70, 0x28, 0x64, 0xc4, 0x25, 0x26, 0xd6, 0xf5, 0xa1, 0x57, 0x0d, 0xba, 0x57, 0x0f, 0xba,
	0xf7, 0xb8, 0x1e, 0xf4, 0xf1, 0xa6, 0xf6, 0xe0, 0xa7, 0x3f, 0x8f, 0x9c, 0xa0, 0xaf, 0xc9, 0x49,
	0x05, 0x92, 0x73, 0xd8, 0x31, 0x89, 0xa6, 0xb4, 0xa0, 0x62, 0x86, 0x89, 0x75, 0xf5, 0xd6, 0x4b,
	0x99, 0x3e, 0xb5, 0x4f, 0x6a, 0x2e, 0x91, 0x69, 0xe1, 0xcc, 0x82, 0xa3, 0x0f, 0xa1, 0x6b, 0x4e,
	0x4d, 0xfa, 0x70, 0xe3, 0x21, 0x16, 0x09, 0x2d, 0xd2, 0xc1, 0x86, 0x5e, 0xd8, 0x52, 0x03, 0x87,
	0x00, 0xf4, 0xf4, 0xe1, 0x30, 0x19, 0xb4, 0xc8, 0x0e, 0x6c, 0x4d, 0x54, 0x1c, 0x23, 0x26, 0x98,
	0x0c, 0xda, 0xa3, 0x5f, 0xdb, 0xb0, 0xbb, 0x78, 0xdf, 0xe4, 0x0c, 0x7a, 0xd3, 0x48, 0x65, 0x52,
	0xb8, 0x1d, 0x63, 0x95, 0xb7, 0x6e, 0x42, 0xbc, 0x2f, 0x8a, 0xef, 0x30, 0x96, 0x98, 0x9c, 0x69,
	0x2c, 0xb0, 0xf4, 0x7f, 0xd8, 0xdf, 0x7d, 0x1d, 0xfb, 0x3f, 0x80, 0xcd, 0xfa, 0x27, 0xc6, 0xed,
	0xad, 0x33, 0xac, 0xf3, 0xb3, 0x36, 0xab, 0x01, 0x86, 0xbf, 0x3b, 0xb0, 0xb3, 0xd0, 0x29, 0x19,
	0xc3, 0x1e, 0xe3, 0x34, 0xa5, 0x45, 0x28, 0x90, 0x5f, 0xd2, 0x18, 0x85, 0xeb, 0x98, 0xf6, 0x6e,
	0x2d, 0x3e, 0xa3, 0x00, 0x05, 0x53, 0x3c, 0xc6, 0x00, 0xa7, 0xc1, 0x6e, 0x45, 0x4c, 0x2c, 0x40,
	0xbe, 0x84, 0xc3, 0x04, 0x85, 0xa4, 0x85, 0x29, 0x72, 0x95, 0xa8, 0xb5, 0x2e, 0xd1, 0xc1, 0x1c,
	0xd6, 0x64, 0x7b, 0x17, 0xba, 0xc6, 0x3d, 0x3b, 0x58, 0x6f, 0x78, 0xcd, 0x0f, 0xc9, 0x9c, 0x4f,
	0x2a, 0x93, 0xd5, 0x39, 0xb4, 0x4b, 0x95, 0x7e, 0xf4, 0x43, 0x1b, 0x06, 0xcb, 0x0e, 0x92, 0x14,
	0x0e, 0x4a, 0xce, 0x72, 0x94, 0x38, 0x43, 0x25, 0x42, 0xc9, 0x69, 0x9a, 0x22, 0xb7, 0x0f, 0xff,
	0xfe, 0xfa, 0x2b, 0xf0, 0x1e, 0x1a, 0x5a, 0xc3, 0x8f, 0x2b, 0xf6, 0x7c, 0x23, 0x20, 0x73, 0x29,
	0xed, 0xee, 0xf0, 0x1f, 0x07, 0xf6, 0x5f, 0xd2, 0x92, 0x37, 0x61, 0x3b, 0x56, 0x42, 0xb2, 0x3c,
	0xfc, 0x5e, 0x21, 0x7f, 0x66, 0x9e, 0xf1, 0xd6, 0xf9, 0x46, 0xd0, 0xaf, 0x76, 0x1f, 0xe9, 0x4d,
	0xf2, 0x36, 0xec, 0xc9, 0x19, 0x47, 0x31, 0x63, 0x59, 0x12, 0x5e, 0x46, 0x99, 0x42, 0x73, 0x76,
	0x27, 0xd8, 0x6d, 0xb6, 0xbf, 0xd6, 0xbb, 0xc4, 0x87, 0x83, 0x98, 0xe5, 0x65, 0xc4, 0xa9, 0x60,
	0x45, 0xc8, 0x4a, 0xe4, 0x91, 0x64, 0xdc, 0xbc, 0x9b, 0xad, 0x80, 0x5c, 0x85, 0xbe, 0xb2, 0x91,
	0xe1, 0x37, 0xb0, 0xf5, 0x00, 0xc5, 0xac, 0x2a, 0x73, 0x13, 0x7a, 0x39, 0x4a, 0x4e, 0xe3, 0xaa,
	0x8b, 0xc0, 0xae, 0xc8, 0x3d, 0xb8, 0x61, 0xaf, 0xcc, 0xda, 0xb2, 0xe2, 0xc6, 0x6a, 0xe5, 0x78,
	0x1b, 0xc0, 0x9c, 0x28, 0x94, 0xcf, 0x4a, 0x1c, 0xef, 0xc3, 0x5e, 0x3d, 0xe7, 0xd6, 0xe1, 0xf1,
	0xdd, 0x5f, 0xfe, 0xba, 0xed, 0x7c, 0xfb, 0xd6, 0xaa, 0x2f, 0x6f, 0xf9, 0x24, 0xb5, 0xdf, 0x86,
	0x8b, 0x9e, 0x99, 0xdd, 0x7b, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x93, 0x3a, 0x93, 0x10, 0xaa,
	0x07, 0x00, 0x00,
}

func (this *Experiment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Experiment)
	if !ok {
		that2, ok := that.(Experiment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Spec.Equal(that1.Spec) {
		return false
	}
	if !this.Result.Equal(&that1.Result) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentResult) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentResult)
	if !ok {
		that2, ok := that.(ExperimentResult)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if len(this.FailureConditions) != len(that1.FailureConditions) {
		return false
	}
	for i := range this.FailureConditions {
		if !this.FailureConditions[i].Equal(that1.FailureConditions[i]) {
			return false
		}
	}
	if !this.TimeStarted.Equal(that1.TimeStarted) {
		return false
	}
	if !this.TimeFinished.Equal(that1.TimeFinished) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentSpec)
	if !ok {
		that2, ok := that.(ExperimentSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Faults) != len(that1.Faults) {
		return false
	}
	for i := range this.Faults {
		if !this.Faults[i].Equal(that1.Faults[i]) {
			return false
		}
	}
	if len(this.FailureConditions) != len(that1.FailureConditions) {
		return false
	}
	for i := range this.FailureConditions {
		if !this.FailureConditions[i].Equal(that1.FailureConditions[i]) {
			return false
		}
	}
	if this.Duration != nil && that1.Duration != nil {
		if *this.Duration != *that1.Duration {
			return false
		}
	} else if this.Duration != nil {
		return false
	} else if that1.Duration != nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentSpec_InjectedFault) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentSpec_InjectedFault)
	if !ok {
		that2, ok := that.(ExperimentSpec_InjectedFault)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.OriginServices) != len(that1.OriginServices) {
		return false
	}
	for i := range this.OriginServices {
		if !this.OriginServices[i].Equal(that1.OriginServices[i]) {
			return false
		}
	}
	if len(this.DestinationServices) != len(that1.DestinationServices) {
		return false
	}
	for i := range this.DestinationServices {
		if !this.DestinationServices[i].Equal(that1.DestinationServices[i]) {
			return false
		}
	}
	if !this.Fault.Equal(that1.Fault) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FailureCondition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition)
	if !ok {
		that2, ok := that.(FailureCondition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.FailureTrigger == nil {
		if this.FailureTrigger != nil {
			return false
		}
	} else if this.FailureTrigger == nil {
		return false
	} else if !this.FailureTrigger.Equal(that1.FailureTrigger) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FailureCondition_PrometeheusTrigger) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_PrometeheusTrigger)
	if !ok {
		that2, ok := that.(FailureCondition_PrometeheusTrigger)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PrometeheusTrigger.Equal(that1.PrometeheusTrigger) {
		return false
	}
	return true
}
func (this *FailureCondition_PrometheusTrigger) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_PrometheusTrigger)
	if !ok {
		that2, ok := that.(FailureCondition_PrometheusTrigger)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.QueryType == nil {
		if this.QueryType != nil {
			return false
		}
	} else if this.QueryType == nil {
		return false
	} else if !this.QueryType.Equal(that1.QueryType) {
		return false
	}
	if this.ThresholdValue != that1.ThresholdValue {
		return false
	}
	if this.ComparisonOperator != that1.ComparisonOperator {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FailureCondition_PrometheusTrigger_CustomQuery) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_PrometheusTrigger_CustomQuery)
	if !ok {
		that2, ok := that.(FailureCondition_PrometheusTrigger_CustomQuery)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CustomQuery != that1.CustomQuery {
		return false
	}
	return true
}
func (this *FailureCondition_PrometheusTrigger_MeshQuery) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_PrometheusTrigger_MeshQuery)
	if !ok {
		that2, ok := that.(FailureCondition_PrometheusTrigger_MeshQuery)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Metric != that1.Metric {
		return false
	}
	if !this.Service.Equal(that1.Service) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
