// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/solo-io/glooshot/api/v1/glooshot.proto

package v1

import (
	bytes "bytes"
	fmt "fmt"
	math "math"
	time "time"

	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	core "github.com/solo-io/solo-kit/pkg/api/v1/resources/core"
	v1 "github.com/solo-io/supergloo/pkg/api/v1"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ExperimentResult_State int32

const (
	// Experiment has not started
	ExperimentResult_Pending ExperimentResult_State = 0
	// Experiment started but threshold not met
	ExperimentResult_Started ExperimentResult_State = 1
	// Experiment failed, threshold was exceeded
	ExperimentResult_Failed ExperimentResult_State = 2
	// Experiment succeeded, duration elapsed
	// If duration is not specified, the Experiment will never
	// be marked Succeeded
	ExperimentResult_Succeeded ExperimentResult_State = 3
)

var ExperimentResult_State_name = map[int32]string{
	0: "Pending",
	1: "Started",
	2: "Failed",
	3: "Succeeded",
}

var ExperimentResult_State_value = map[string]int32{
	"Pending":   0,
	"Started":   1,
	"Failed":    2,
	"Succeeded": 3,
}

func (x ExperimentResult_State) String() string {
	return proto.EnumName(ExperimentResult_State_name, int32(x))
}

func (ExperimentResult_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{1, 0}
}

//
//Describes an Experiment that GlooShot should run
type Experiment struct {
	// the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	// indicates whether or not the spec is valid
	// set by glooshot, intended to be read by clients
	Status core.Status `protobuf:"bytes,3,opt,name=status,proto3" json:"status"`
	// configuration for the Experiment
	Spec *ExperimentSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// the result of the experiment
	Result               ExperimentResult `protobuf:"bytes,4,opt,name=result,proto3" json:"result"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Experiment) Reset()         { *m = Experiment{} }
func (m *Experiment) String() string { return proto.CompactTextString(m) }
func (*Experiment) ProtoMessage()    {}
func (*Experiment) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{0}
}
func (m *Experiment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Experiment.Unmarshal(m, b)
}
func (m *Experiment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Experiment.Marshal(b, m, deterministic)
}
func (m *Experiment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Experiment.Merge(m, src)
}
func (m *Experiment) XXX_Size() int {
	return xxx_messageInfo_Experiment.Size(m)
}
func (m *Experiment) XXX_DiscardUnknown() {
	xxx_messageInfo_Experiment.DiscardUnknown(m)
}

var xxx_messageInfo_Experiment proto.InternalMessageInfo

func (m *Experiment) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Experiment) GetStatus() core.Status {
	if m != nil {
		return m.Status
	}
	return core.Status{}
}

func (m *Experiment) GetSpec() *ExperimentSpec {
	if m != nil {
		return m.Spec
	}
	return nil
}

func (m *Experiment) GetResult() ExperimentResult {
	if m != nil {
		return m.Result
	}
	return ExperimentResult{}
}

type ExperimentResult struct {
	// the current state of the experiment as reported by glooshot
	State ExperimentResult_State `protobuf:"varint,1,opt,name=state,proto3,enum=glooshot.solo.io.ExperimentResult_State" json:"state,omitempty"`
	// arbitrary data summarizing a failure in case one occurred
	FailureReport map[string]string `protobuf:"bytes,2,rep,name=failure_report,json=failureReport,proto3" json:"failure_report,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// time the experiment was started
	TimeStarted *types.Timestamp `protobuf:"bytes,3,opt,name=time_started,json=timeStarted,proto3" json:"time_started,omitempty"`
	// the time the experiment completed
	TimeFinished         *types.Timestamp `protobuf:"bytes,4,opt,name=time_finished,json=timeFinished,proto3" json:"time_finished,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ExperimentResult) Reset()         { *m = ExperimentResult{} }
func (m *ExperimentResult) String() string { return proto.CompactTextString(m) }
func (*ExperimentResult) ProtoMessage()    {}
func (*ExperimentResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{1}
}
func (m *ExperimentResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentResult.Unmarshal(m, b)
}
func (m *ExperimentResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentResult.Marshal(b, m, deterministic)
}
func (m *ExperimentResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentResult.Merge(m, src)
}
func (m *ExperimentResult) XXX_Size() int {
	return xxx_messageInfo_ExperimentResult.Size(m)
}
func (m *ExperimentResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentResult proto.InternalMessageInfo

func (m *ExperimentResult) GetState() ExperimentResult_State {
	if m != nil {
		return m.State
	}
	return ExperimentResult_Pending
}

func (m *ExperimentResult) GetFailureReport() map[string]string {
	if m != nil {
		return m.FailureReport
	}
	return nil
}

func (m *ExperimentResult) GetTimeStarted() *types.Timestamp {
	if m != nil {
		return m.TimeStarted
	}
	return nil
}

func (m *ExperimentResult) GetTimeFinished() *types.Timestamp {
	if m != nil {
		return m.TimeFinished
	}
	return nil
}

type ExperimentSpec struct {
	// the faults this experiment will inject
	// if empty, Glooshot will run a "control" experiment with no faults injected
	Faults []*ExperimentSpec_InjectedFault `protobuf:"bytes,4,rep,name=faults,proto3" json:"faults,omitempty"`
	// conditions on which to stop the experiment and mark it as failed
	// at least one must be specified
	FailureConditions []*FailureCondition `protobuf:"bytes,5,rep,name=failure_conditions,json=failureConditions,proto3" json:"failure_conditions,omitempty"`
	// the duration for which to run the experiment
	// if missing or set to 0 the experiment will run indefinitely
	// only Experiments with a timeout can succeed
	Duration *time.Duration `protobuf:"bytes,6,opt,name=duration,proto3,stdduration" json:"duration,omitempty"`
	// The mesh to which the experiment will be applied. Must match a mesh.supergloo.solo.io CRD. If a cluster only has
	// a single mesh, this value is not needed, Glooshot will default to the only possible option.
	TargetMesh           *core.ResourceRef `protobuf:"bytes,7,opt,name=target_mesh,json=targetMesh,proto3" json:"target_mesh,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ExperimentSpec) Reset()         { *m = ExperimentSpec{} }
func (m *ExperimentSpec) String() string { return proto.CompactTextString(m) }
func (*ExperimentSpec) ProtoMessage()    {}
func (*ExperimentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{2}
}
func (m *ExperimentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentSpec.Unmarshal(m, b)
}
func (m *ExperimentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentSpec.Marshal(b, m, deterministic)
}
func (m *ExperimentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentSpec.Merge(m, src)
}
func (m *ExperimentSpec) XXX_Size() int {
	return xxx_messageInfo_ExperimentSpec.Size(m)
}
func (m *ExperimentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentSpec proto.InternalMessageInfo

func (m *ExperimentSpec) GetFaults() []*ExperimentSpec_InjectedFault {
	if m != nil {
		return m.Faults
	}
	return nil
}

func (m *ExperimentSpec) GetFailureConditions() []*FailureCondition {
	if m != nil {
		return m.FailureConditions
	}
	return nil
}

func (m *ExperimentSpec) GetDuration() *time.Duration {
	if m != nil {
		return m.Duration
	}
	return nil
}

func (m *ExperimentSpec) GetTargetMesh() *core.ResourceRef {
	if m != nil {
		return m.TargetMesh
	}
	return nil
}

// decribes a single fault to  inject
type ExperimentSpec_InjectedFault struct {
	// if specified, the fault will only apply to requests sent from these services
	OriginServices []*core.ResourceRef `protobuf:"bytes,1,rep,name=origin_services,json=originServices,proto3" json:"origin_services,omitempty"`
	// if specified, the fault will only apply to requests sent to these services
	DestinationServices []*core.ResourceRef `protobuf:"bytes,2,rep,name=destination_services,json=destinationServices,proto3" json:"destination_services,omitempty"`
	// the type of fault to inject
	Fault                *v1.FaultInjection `protobuf:"bytes,3,opt,name=fault,proto3" json:"fault,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ExperimentSpec_InjectedFault) Reset()         { *m = ExperimentSpec_InjectedFault{} }
func (m *ExperimentSpec_InjectedFault) String() string { return proto.CompactTextString(m) }
func (*ExperimentSpec_InjectedFault) ProtoMessage()    {}
func (*ExperimentSpec_InjectedFault) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{2, 0}
}
func (m *ExperimentSpec_InjectedFault) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Unmarshal(m, b)
}
func (m *ExperimentSpec_InjectedFault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Marshal(b, m, deterministic)
}
func (m *ExperimentSpec_InjectedFault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExperimentSpec_InjectedFault.Merge(m, src)
}
func (m *ExperimentSpec_InjectedFault) XXX_Size() int {
	return xxx_messageInfo_ExperimentSpec_InjectedFault.Size(m)
}
func (m *ExperimentSpec_InjectedFault) XXX_DiscardUnknown() {
	xxx_messageInfo_ExperimentSpec_InjectedFault.DiscardUnknown(m)
}

var xxx_messageInfo_ExperimentSpec_InjectedFault proto.InternalMessageInfo

func (m *ExperimentSpec_InjectedFault) GetOriginServices() []*core.ResourceRef {
	if m != nil {
		return m.OriginServices
	}
	return nil
}

func (m *ExperimentSpec_InjectedFault) GetDestinationServices() []*core.ResourceRef {
	if m != nil {
		return m.DestinationServices
	}
	return nil
}

func (m *ExperimentSpec_InjectedFault) GetFault() *v1.FaultInjection {
	if m != nil {
		return m.Fault
	}
	return nil
}

// a condition based on an observed prometheus metric
type FailureCondition struct {
	// Types that are valid to be assigned to FailureTrigger:
	//	*FailureCondition_WebhookUrl
	//	*FailureCondition_PrometheusTrigger
	FailureTrigger       isFailureCondition_FailureTrigger `protobuf_oneof:"failure_trigger"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *FailureCondition) Reset()         { *m = FailureCondition{} }
func (m *FailureCondition) String() string { return proto.CompactTextString(m) }
func (*FailureCondition) ProtoMessage()    {}
func (*FailureCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{3}
}
func (m *FailureCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FailureCondition.Unmarshal(m, b)
}
func (m *FailureCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FailureCondition.Marshal(b, m, deterministic)
}
func (m *FailureCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FailureCondition.Merge(m, src)
}
func (m *FailureCondition) XXX_Size() int {
	return xxx_messageInfo_FailureCondition.Size(m)
}
func (m *FailureCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_FailureCondition.DiscardUnknown(m)
}

var xxx_messageInfo_FailureCondition proto.InternalMessageInfo

type isFailureCondition_FailureTrigger interface {
	isFailureCondition_FailureTrigger()
	Equal(interface{}) bool
}

type FailureCondition_WebhookUrl struct {
	WebhookUrl string `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3,oneof"`
}
type FailureCondition_PrometheusTrigger struct {
	PrometheusTrigger *PrometheusTrigger `protobuf:"bytes,2,opt,name=prometheus_trigger,json=prometheusTrigger,proto3,oneof"`
}

func (*FailureCondition_WebhookUrl) isFailureCondition_FailureTrigger()        {}
func (*FailureCondition_PrometheusTrigger) isFailureCondition_FailureTrigger() {}

func (m *FailureCondition) GetFailureTrigger() isFailureCondition_FailureTrigger {
	if m != nil {
		return m.FailureTrigger
	}
	return nil
}

func (m *FailureCondition) GetWebhookUrl() string {
	if x, ok := m.GetFailureTrigger().(*FailureCondition_WebhookUrl); ok {
		return x.WebhookUrl
	}
	return ""
}

func (m *FailureCondition) GetPrometheusTrigger() *PrometheusTrigger {
	if x, ok := m.GetFailureTrigger().(*FailureCondition_PrometheusTrigger); ok {
		return x.PrometheusTrigger
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*FailureCondition) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _FailureCondition_OneofMarshaler, _FailureCondition_OneofUnmarshaler, _FailureCondition_OneofSizer, []interface{}{
		(*FailureCondition_WebhookUrl)(nil),
		(*FailureCondition_PrometheusTrigger)(nil),
	}
}

func _FailureCondition_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*FailureCondition)
	// failure_trigger
	switch x := m.FailureTrigger.(type) {
	case *FailureCondition_WebhookUrl:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.WebhookUrl)
	case *FailureCondition_PrometheusTrigger:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PrometheusTrigger); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("FailureCondition.FailureTrigger has unexpected type %T", x)
	}
	return nil
}

func _FailureCondition_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*FailureCondition)
	switch tag {
	case 1: // failure_trigger.webhook_url
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.FailureTrigger = &FailureCondition_WebhookUrl{x}
		return true, err
	case 2: // failure_trigger.prometheus_trigger
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PrometheusTrigger)
		err := b.DecodeMessage(msg)
		m.FailureTrigger = &FailureCondition_PrometheusTrigger{msg}
		return true, err
	default:
		return false, nil
	}
}

func _FailureCondition_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*FailureCondition)
	// failure_trigger
	switch x := m.FailureTrigger.(type) {
	case *FailureCondition_WebhookUrl:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.WebhookUrl)))
		n += len(x.WebhookUrl)
	case *FailureCondition_PrometheusTrigger:
		s := proto.Size(x.PrometheusTrigger)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PrometheusTrigger struct {
	// Types that are valid to be assigned to QueryType:
	//	*PrometheusTrigger_CustomQuery
	//	*PrometheusTrigger_SuccessRate
	QueryType isPrometheusTrigger_QueryType `protobuf_oneof:"query_type"`
	// consider the failure condition met if the metric falls below this threshold
	ThresholdValue float64 `protobuf:"fixed64,3,opt,name=threshold_value,json=thresholdValue,proto3" json:"threshold_value,omitempty"`
	// the comparison operator to use when comparing the threshold and observed metric values
	// if the comparison evaluates to true, the failure condition will be considered met
	// possible values are '==', '>', '<', '>=', and '<='
	// defaults to '<'
	ComparisonOperator   string   `protobuf:"bytes,4,opt,name=comparison_operator,json=comparisonOperator,proto3" json:"comparison_operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrometheusTrigger) Reset()         { *m = PrometheusTrigger{} }
func (m *PrometheusTrigger) String() string { return proto.CompactTextString(m) }
func (*PrometheusTrigger) ProtoMessage()    {}
func (*PrometheusTrigger) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{4}
}
func (m *PrometheusTrigger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrometheusTrigger.Unmarshal(m, b)
}
func (m *PrometheusTrigger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrometheusTrigger.Marshal(b, m, deterministic)
}
func (m *PrometheusTrigger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrometheusTrigger.Merge(m, src)
}
func (m *PrometheusTrigger) XXX_Size() int {
	return xxx_messageInfo_PrometheusTrigger.Size(m)
}
func (m *PrometheusTrigger) XXX_DiscardUnknown() {
	xxx_messageInfo_PrometheusTrigger.DiscardUnknown(m)
}

var xxx_messageInfo_PrometheusTrigger proto.InternalMessageInfo

type isPrometheusTrigger_QueryType interface {
	isPrometheusTrigger_QueryType()
	Equal(interface{}) bool
}

type PrometheusTrigger_CustomQuery struct {
	CustomQuery string `protobuf:"bytes,1,opt,name=custom_query,json=customQuery,proto3,oneof"`
}
type PrometheusTrigger_SuccessRate struct {
	SuccessRate *PrometheusTrigger_SuccessRateQuery `protobuf:"bytes,2,opt,name=success_rate,json=successRate,proto3,oneof"`
}

func (*PrometheusTrigger_CustomQuery) isPrometheusTrigger_QueryType() {}
func (*PrometheusTrigger_SuccessRate) isPrometheusTrigger_QueryType() {}

func (m *PrometheusTrigger) GetQueryType() isPrometheusTrigger_QueryType {
	if m != nil {
		return m.QueryType
	}
	return nil
}

func (m *PrometheusTrigger) GetCustomQuery() string {
	if x, ok := m.GetQueryType().(*PrometheusTrigger_CustomQuery); ok {
		return x.CustomQuery
	}
	return ""
}

func (m *PrometheusTrigger) GetSuccessRate() *PrometheusTrigger_SuccessRateQuery {
	if x, ok := m.GetQueryType().(*PrometheusTrigger_SuccessRate); ok {
		return x.SuccessRate
	}
	return nil
}

func (m *PrometheusTrigger) GetThresholdValue() float64 {
	if m != nil {
		return m.ThresholdValue
	}
	return 0
}

func (m *PrometheusTrigger) GetComparisonOperator() string {
	if m != nil {
		return m.ComparisonOperator
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PrometheusTrigger) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PrometheusTrigger_OneofMarshaler, _PrometheusTrigger_OneofUnmarshaler, _PrometheusTrigger_OneofSizer, []interface{}{
		(*PrometheusTrigger_CustomQuery)(nil),
		(*PrometheusTrigger_SuccessRate)(nil),
	}
}

func _PrometheusTrigger_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PrometheusTrigger)
	// query_type
	switch x := m.QueryType.(type) {
	case *PrometheusTrigger_CustomQuery:
		_ = b.EncodeVarint(1<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.CustomQuery)
	case *PrometheusTrigger_SuccessRate:
		_ = b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SuccessRate); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PrometheusTrigger.QueryType has unexpected type %T", x)
	}
	return nil
}

func _PrometheusTrigger_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PrometheusTrigger)
	switch tag {
	case 1: // query_type.custom_query
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.QueryType = &PrometheusTrigger_CustomQuery{x}
		return true, err
	case 2: // query_type.success_rate
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PrometheusTrigger_SuccessRateQuery)
		err := b.DecodeMessage(msg)
		m.QueryType = &PrometheusTrigger_SuccessRate{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PrometheusTrigger_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PrometheusTrigger)
	// query_type
	switch x := m.QueryType.(type) {
	case *PrometheusTrigger_CustomQuery:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.CustomQuery)))
		n += len(x.CustomQuery)
	case *PrometheusTrigger_SuccessRate:
		s := proto.Size(x.SuccessRate)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// returns the # of non-5XX requests / total requests for the given interval
type PrometheusTrigger_SuccessRateQuery struct {
	// the service whose success rate Glooshot should monitor
	Service *core.ResourceRef `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	// the time interval over which the success rate should be measured
	// defaults to 1 minute
	Interval             *time.Duration `protobuf:"bytes,6,opt,name=interval,proto3,stdduration" json:"interval,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PrometheusTrigger_SuccessRateQuery) Reset()         { *m = PrometheusTrigger_SuccessRateQuery{} }
func (m *PrometheusTrigger_SuccessRateQuery) String() string { return proto.CompactTextString(m) }
func (*PrometheusTrigger_SuccessRateQuery) ProtoMessage()    {}
func (*PrometheusTrigger_SuccessRateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{4, 0}
}
func (m *PrometheusTrigger_SuccessRateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrometheusTrigger_SuccessRateQuery.Unmarshal(m, b)
}
func (m *PrometheusTrigger_SuccessRateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrometheusTrigger_SuccessRateQuery.Marshal(b, m, deterministic)
}
func (m *PrometheusTrigger_SuccessRateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrometheusTrigger_SuccessRateQuery.Merge(m, src)
}
func (m *PrometheusTrigger_SuccessRateQuery) XXX_Size() int {
	return xxx_messageInfo_PrometheusTrigger_SuccessRateQuery.Size(m)
}
func (m *PrometheusTrigger_SuccessRateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_PrometheusTrigger_SuccessRateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_PrometheusTrigger_SuccessRateQuery proto.InternalMessageInfo

func (m *PrometheusTrigger_SuccessRateQuery) GetService() *core.ResourceRef {
	if m != nil {
		return m.Service
	}
	return nil
}

func (m *PrometheusTrigger_SuccessRateQuery) GetInterval() *time.Duration {
	if m != nil {
		return m.Interval
	}
	return nil
}

// a snapshot of experiment metric values
type Report struct {
	// the object metadata for this resource
	Metadata core.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata"`
	// Name of the experiment this report pertains to
	Experiment *core.ResourceRef `protobuf:"bytes,2,opt,name=experiment,proto3" json:"experiment,omitempty"`
	// the measured values of each of the failure conditions at the time the report was captured
	FailureConditionHistory []*Report_FailureConditionHistory `protobuf:"bytes,3,rep,name=failure_condition_history,json=failureConditionHistory,proto3" json:"failure_condition_history,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}                          `json:"-"`
	XXX_unrecognized        []byte                            `json:"-"`
	XXX_sizecache           int32                             `json:"-"`
}

func (m *Report) Reset()         { *m = Report{} }
func (m *Report) String() string { return proto.CompactTextString(m) }
func (*Report) ProtoMessage()    {}
func (*Report) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{5}
}
func (m *Report) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report.Unmarshal(m, b)
}
func (m *Report) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report.Marshal(b, m, deterministic)
}
func (m *Report) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report.Merge(m, src)
}
func (m *Report) XXX_Size() int {
	return xxx_messageInfo_Report.Size(m)
}
func (m *Report) XXX_DiscardUnknown() {
	xxx_messageInfo_Report.DiscardUnknown(m)
}

var xxx_messageInfo_Report proto.InternalMessageInfo

func (m *Report) GetMetadata() core.Metadata {
	if m != nil {
		return m.Metadata
	}
	return core.Metadata{}
}

func (m *Report) GetExperiment() *core.ResourceRef {
	if m != nil {
		return m.Experiment
	}
	return nil
}

func (m *Report) GetFailureConditionHistory() []*Report_FailureConditionHistory {
	if m != nil {
		return m.FailureConditionHistory
	}
	return nil
}

type Report_FailureConditionSnapshot struct {
	// return type for simple metrics queries
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// time that value was recorded
	Timestamp            *types.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Report_FailureConditionSnapshot) Reset()         { *m = Report_FailureConditionSnapshot{} }
func (m *Report_FailureConditionSnapshot) String() string { return proto.CompactTextString(m) }
func (*Report_FailureConditionSnapshot) ProtoMessage()    {}
func (*Report_FailureConditionSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{5, 0}
}
func (m *Report_FailureConditionSnapshot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_FailureConditionSnapshot.Unmarshal(m, b)
}
func (m *Report_FailureConditionSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_FailureConditionSnapshot.Marshal(b, m, deterministic)
}
func (m *Report_FailureConditionSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_FailureConditionSnapshot.Merge(m, src)
}
func (m *Report_FailureConditionSnapshot) XXX_Size() int {
	return xxx_messageInfo_Report_FailureConditionSnapshot.Size(m)
}
func (m *Report_FailureConditionSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_FailureConditionSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_Report_FailureConditionSnapshot proto.InternalMessageInfo

func (m *Report_FailureConditionSnapshot) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Report_FailureConditionSnapshot) GetTimestamp() *types.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type Report_FailureConditionHistory struct {
	// name of the corresponding failure condition
	// TODO - add name to spec, using array index for now
	FailureConditionName string `protobuf:"bytes,1,opt,name=failure_condition_name,json=failureConditionName,proto3" json:"failure_condition_name,omitempty"`
	// history of all measurements of the failure condition
	FailureConditionSnapshots []*Report_FailureConditionSnapshot `protobuf:"bytes,2,rep,name=failure_condition_snapshots,json=failureConditionSnapshots,proto3" json:"failure_condition_snapshots,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}                           `json:"-"`
	XXX_unrecognized          []byte                             `json:"-"`
	XXX_sizecache             int32                              `json:"-"`
}

func (m *Report_FailureConditionHistory) Reset()         { *m = Report_FailureConditionHistory{} }
func (m *Report_FailureConditionHistory) String() string { return proto.CompactTextString(m) }
func (*Report_FailureConditionHistory) ProtoMessage()    {}
func (*Report_FailureConditionHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9da8418b9c75752, []int{5, 1}
}
func (m *Report_FailureConditionHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Report_FailureConditionHistory.Unmarshal(m, b)
}
func (m *Report_FailureConditionHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Report_FailureConditionHistory.Marshal(b, m, deterministic)
}
func (m *Report_FailureConditionHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Report_FailureConditionHistory.Merge(m, src)
}
func (m *Report_FailureConditionHistory) XXX_Size() int {
	return xxx_messageInfo_Report_FailureConditionHistory.Size(m)
}
func (m *Report_FailureConditionHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_Report_FailureConditionHistory.DiscardUnknown(m)
}

var xxx_messageInfo_Report_FailureConditionHistory proto.InternalMessageInfo

func (m *Report_FailureConditionHistory) GetFailureConditionName() string {
	if m != nil {
		return m.FailureConditionName
	}
	return ""
}

func (m *Report_FailureConditionHistory) GetFailureConditionSnapshots() []*Report_FailureConditionSnapshot {
	if m != nil {
		return m.FailureConditionSnapshots
	}
	return nil
}

func init() {
	proto.RegisterEnum("glooshot.solo.io.ExperimentResult_State", ExperimentResult_State_name, ExperimentResult_State_value)
	proto.RegisterType((*Experiment)(nil), "glooshot.solo.io.Experiment")
	proto.RegisterType((*ExperimentResult)(nil), "glooshot.solo.io.ExperimentResult")
	proto.RegisterMapType((map[string]string)(nil), "glooshot.solo.io.ExperimentResult.FailureReportEntry")
	proto.RegisterType((*ExperimentSpec)(nil), "glooshot.solo.io.ExperimentSpec")
	proto.RegisterType((*ExperimentSpec_InjectedFault)(nil), "glooshot.solo.io.ExperimentSpec.InjectedFault")
	proto.RegisterType((*FailureCondition)(nil), "glooshot.solo.io.FailureCondition")
	proto.RegisterType((*PrometheusTrigger)(nil), "glooshot.solo.io.PrometheusTrigger")
	proto.RegisterType((*PrometheusTrigger_SuccessRateQuery)(nil), "glooshot.solo.io.PrometheusTrigger.SuccessRateQuery")
	proto.RegisterType((*Report)(nil), "glooshot.solo.io.Report")
	proto.RegisterType((*Report_FailureConditionSnapshot)(nil), "glooshot.solo.io.Report.FailureConditionSnapshot")
	proto.RegisterType((*Report_FailureConditionHistory)(nil), "glooshot.solo.io.Report.FailureConditionHistory")
}

func init() {
	proto.RegisterFile("github.com/solo-io/glooshot/api/v1/glooshot.proto", fileDescriptor_b9da8418b9c75752)
}

var fileDescriptor_b9da8418b9c75752 = []byte{
	// 1099 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x4f, 0x6f, 0xe3, 0x44,
	0x14, 0xaf, 0xf3, 0xaf, 0xcd, 0x4b, 0xff, 0xa4, 0xb3, 0xd5, 0xae, 0x1b, 0xa4, 0x6d, 0x37, 0x2b,
	0x41, 0x0f, 0x8b, 0x43, 0xbb, 0x45, 0x94, 0xf2, 0x6f, 0x15, 0xd8, 0xaa, 0x48, 0x2c, 0xec, 0x3a,
	0x05, 0x09, 0x84, 0x64, 0xb9, 0xf6, 0x8b, 0xe3, 0xad, 0xe3, 0xf1, 0xce, 0x8c, 0xcb, 0xf6, 0x48,
	0xc5, 0x99, 0x33, 0x27, 0xce, 0x1c, 0xb9, 0x71, 0xe7, 0xc4, 0x67, 0xe0, 0x00, 0x12, 0xdf, 0xa0,
	0xdf, 0x00, 0x79, 0x66, 0xec, 0xb4, 0x49, 0x37, 0x0d, 0x9c, 0x92, 0x79, 0xef, 0xf7, 0x7b, 0xf3,
	0xe6, 0xf7, 0xde, 0xbc, 0x31, 0x6c, 0x07, 0xa1, 0x18, 0xa4, 0xc7, 0x96, 0x47, 0x87, 0x1d, 0x4e,
	0x23, 0xfa, 0x66, 0x48, 0x3b, 0x41, 0x44, 0x29, 0x1f, 0x50, 0xd1, 0x71, 0x93, 0xb0, 0x73, 0xba,
	0x5d, 0xac, 0xad, 0x84, 0x51, 0x41, 0x49, 0xb3, 0x58, 0x67, 0x04, 0x2b, 0xa4, 0xad, 0xb5, 0x80,
	0x06, 0x54, 0x3a, 0x3b, 0xd9, 0x3f, 0x85, 0x6b, 0xdd, 0x0d, 0x28, 0x0d, 0x22, 0xec, 0xc8, 0xd5,
	0x71, 0xda, 0xef, 0xf8, 0x29, 0x73, 0x45, 0x48, 0x63, 0xed, 0xdf, 0x18, 0xf7, 0x8b, 0x70, 0x88,
	0x5c, 0xb8, 0xc3, 0x44, 0x03, 0x3a, 0xd7, 0xe4, 0x26, 0x7f, 0x4f, 0xc2, 0x22, 0x37, 0x2e, 0x5c,
	0x91, 0x72, 0x4d, 0xd8, 0x9e, 0x81, 0x30, 0x44, 0xe1, 0xfa, 0xae, 0x70, 0x35, 0xe5, 0xc1, 0x0c,
	0x14, 0x86, 0xfd, 0xff, 0xb0, 0x41, 0xbe, 0x9e, 0x46, 0x49, 0x13, 0x64, 0x99, 0x8a, 0xc5, 0x0e,
	0x34, 0x15, 0x61, 0x1c, 0x28, 0x4a, 0xfb, 0xc7, 0x12, 0xc0, 0xe3, 0x97, 0x09, 0xb2, 0x70, 0x88,
	0xb1, 0x20, 0x7b, 0xb0, 0x90, 0x27, 0x6d, 0x1a, 0x9b, 0xc6, 0x56, 0x63, 0xe7, 0xb6, 0xe5, 0x51,
	0x86, 0xb9, 0xfc, 0xd6, 0x13, 0xed, 0xed, 0x56, 0xfe, 0xf8, 0x6b, 0x63, 0xce, 0x2e, 0xd0, 0x64,
	0x07, 0x6a, 0x4a, 0x1f, 0xb3, 0x2c, 0x79, 0x6b, 0x57, 0x79, 0x3d, 0xe9, 0xd3, 0x2c, 0x8d, 0x24,
	0xbb, 0x50, 0xe1, 0x09, 0x7a, 0x66, 0x49, 0x32, 0x36, 0xad, 0xf1, 0x62, 0x5b, 0xa3, 0xcc, 0x7a,
	0x09, 0x7a, 0xb6, 0x44, 0x93, 0x47, 0x50, 0x63, 0xc8, 0xd3, 0x48, 0x98, 0x15, 0xc9, 0x6b, 0x4f,
	0xe3, 0xd9, 0x12, 0x99, 0xef, 0xab, 0x78, 0xfb, 0xad, 0xf3, 0x8b, 0x4a, 0x15, 0xca, 0xf8, 0x32,
	0x39, 0xbf, 0xa8, 0x2c, 0x91, 0x06, 0x16, 0x70, 0xde, 0xfe, 0xb5, 0x0c, 0xcd, 0x71, 0x3a, 0xf9,
	0x10, 0xaa, 0x59, 0xca, 0x28, 0x35, 0x59, 0xde, 0xd9, 0xba, 0x79, 0x47, 0x79, 0x60, 0xb4, 0x15,
	0x8d, 0x7c, 0x0b, 0xcb, 0x7d, 0x37, 0x8c, 0x52, 0x86, 0x0e, 0xc3, 0x84, 0x32, 0x61, 0x96, 0x36,
	0xcb, 0x5b, 0x8d, 0x9d, 0xb7, 0x67, 0x08, 0x74, 0xa0, 0x88, 0xb6, 0xe4, 0x3d, 0x8e, 0x05, 0x3b,
	0xb3, 0x97, 0xfa, 0x97, 0x6d, 0xe4, 0x03, 0x58, 0xcc, 0xda, 0xd9, 0xe1, 0xc2, 0x65, 0x02, 0x7d,
	0x5d, 0x80, 0x96, 0xa5, 0x7a, 0xde, 0xca, 0x7b, 0xde, 0x3a, 0xca, 0x7b, 0xde, 0x6e, 0x64, 0xf8,
	0x9e, 0x82, 0x93, 0x8f, 0x60, 0x49, 0xd2, 0xfb, 0x61, 0x1c, 0xf2, 0x01, 0xfa, 0x5a, 0xd6, 0x69,
	0x7c, 0xb9, 0xdf, 0x81, 0xc6, 0xb7, 0x1e, 0x01, 0x99, 0x4c, 0x92, 0x34, 0xa1, 0x7c, 0x82, 0x67,
	0x52, 0xb1, 0xba, 0x9d, 0xfd, 0x25, 0x6b, 0x50, 0x3d, 0x75, 0xa3, 0x14, 0x65, 0xbd, 0xeb, 0xb6,
	0x5a, 0xec, 0x97, 0xf6, 0x8c, 0xf6, 0xfb, 0x50, 0x95, 0x7a, 0x91, 0x06, 0xcc, 0x3f, 0xc5, 0xd8,
	0x0f, 0xe3, 0xa0, 0x39, 0x97, 0x2d, 0x74, 0x8e, 0x4d, 0x83, 0x00, 0xd4, 0xb2, 0x4d, 0xd0, 0x6f,
	0x96, 0xc8, 0x12, 0xd4, 0x7b, 0xa9, 0xe7, 0x21, 0xfa, 0xe8, 0x37, 0xcb, 0xed, 0xef, 0x2b, 0xb0,
	0x7c, 0xb5, 0x53, 0xc8, 0x01, 0xd4, 0xfa, 0x6e, 0x1a, 0x09, 0x6e, 0x56, 0xa4, 0xd0, 0xd6, 0x4d,
	0xbd, 0x65, 0x7d, 0x1a, 0x3f, 0x47, 0x4f, 0xa0, 0x7f, 0x90, 0xd1, 0x6c, 0xcd, 0x26, 0xcf, 0x80,
	0xe4, 0x85, 0xf3, 0x68, 0xec, 0x87, 0xd9, 0x48, 0xe1, 0x66, 0x55, 0xc6, 0xbc, 0xa6, 0xef, 0xb4,
	0x0c, 0x1f, 0xe7, 0x50, 0x7b, 0xb5, 0x3f, 0x66, 0xe1, 0xe4, 0x3d, 0x58, 0xc8, 0x87, 0x93, 0x59,
	0x93, 0x4a, 0xaf, 0x4f, 0x28, 0xfd, 0x89, 0x06, 0x74, 0x2b, 0x3f, 0xfd, 0xbd, 0x61, 0xd8, 0x05,
	0x81, 0xec, 0x43, 0x43, 0xb8, 0x2c, 0x40, 0xe1, 0x0c, 0x91, 0x0f, 0xcc, 0x79, 0xcd, 0xbf, 0x72,
	0xd5, 0x6c, 0xe4, 0x34, 0x65, 0x1e, 0xda, 0xd8, 0xb7, 0x41, 0xa1, 0x9f, 0x20, 0x1f, 0xb4, 0xfe,
	0x34, 0x60, 0xe9, 0xca, 0x29, 0x49, 0x17, 0x56, 0x28, 0x0b, 0x83, 0x30, 0x76, 0x38, 0xb2, 0xd3,
	0xd0, 0x43, 0x6e, 0x1a, 0xf2, 0x68, 0x53, 0x22, 0x2e, 0x2b, 0x46, 0x4f, 0x13, 0xc8, 0x67, 0xb0,
	0xe6, 0x23, 0x17, 0x61, 0x2c, 0x13, 0x1c, 0x05, 0x2a, 0xdd, 0x14, 0xe8, 0xd6, 0x25, 0x5a, 0x11,
	0xed, 0x1d, 0xa8, 0x4a, 0xe5, 0x75, 0x0f, 0xdf, 0xb3, 0x8a, 0xf1, 0x75, 0x49, 0xe3, 0x34, 0x12,
	0xea, 0x1c, 0x99, 0xc2, 0x0a, 0xdf, 0xfe, 0xd9, 0x80, 0xe6, 0xb8, 0xfa, 0xe4, 0x1e, 0x34, 0xbe,
	0xc3, 0xe3, 0x01, 0xa5, 0x27, 0x4e, 0xca, 0x22, 0xd5, 0x8a, 0x87, 0x73, 0x36, 0x68, 0xe3, 0x97,
	0x2c, 0x22, 0x47, 0x40, 0x12, 0x46, 0x87, 0x28, 0x06, 0x98, 0x72, 0x47, 0xb0, 0x30, 0x08, 0x90,
	0xe9, 0x81, 0x74, 0x7f, 0xb2, 0xc0, 0x4f, 0x0b, 0xec, 0x91, 0x82, 0x1e, 0xce, 0xd9, 0xab, 0xc9,
	0xb8, 0xb1, 0xbb, 0x0a, 0x2b, 0x79, 0xdb, 0xe8, 0x90, 0xed, 0xf3, 0x32, 0xac, 0x4e, 0xb0, 0xc9,
	0x7d, 0x58, 0xf4, 0x52, 0x2e, 0xe8, 0xd0, 0x79, 0x91, 0x22, 0x3b, 0x2b, 0x52, 0x6c, 0x28, 0xeb,
	0xb3, 0xcc, 0x48, 0xbe, 0x86, 0x45, 0x9e, 0xb5, 0x3b, 0xe7, 0x0e, 0xcb, 0x86, 0x90, 0xca, 0x6e,
	0x77, 0x86, 0xec, 0xac, 0x9e, 0xe2, 0xd9, 0xae, 0x40, 0x19, 0x2b, 0x0b, 0xcd, 0x47, 0x36, 0xf2,
	0x06, 0xac, 0x88, 0x01, 0x43, 0x3e, 0xa0, 0x91, 0xef, 0xa8, 0xcb, 0x99, 0x29, 0x6f, 0xd8, 0xcb,
	0x85, 0xf9, 0xab, 0xcc, 0x4a, 0x3a, 0x70, 0xcb, 0xa3, 0xc3, 0xc4, 0x65, 0x21, 0xa7, 0xb1, 0x43,
	0x13, 0x64, 0xae, 0xa0, 0x4c, 0x8e, 0x8a, 0xba, 0x4d, 0x46, 0xae, 0x2f, 0xb4, 0xa7, 0xf5, 0x83,
	0x01, 0xcd, 0xf1, 0xdd, 0xc9, 0x43, 0x98, 0xd7, 0x0d, 0xa2, 0x5f, 0x97, 0x29, 0xfd, 0x91, 0x23,
	0xb3, 0x0b, 0x13, 0xc6, 0x02, 0xd9, 0xa9, 0x1b, 0xcd, 0x7c, 0x61, 0x72, 0x42, 0x77, 0x11, 0x40,
	0x2a, 0xeb, 0x88, 0xb3, 0x04, 0xdb, 0xbf, 0x55, 0xa0, 0xa6, 0x87, 0xe6, 0xff, 0x7f, 0xe9, 0xde,
	0x05, 0x18, 0x3d, 0x18, 0xba, 0x18, 0xd3, 0xae, 0xe0, 0x08, 0x4c, 0x22, 0x58, 0x9f, 0x18, 0x27,
	0xce, 0x20, 0xe4, 0x82, 0xb2, 0x33, 0xb3, 0x2c, 0x6f, 0xcc, 0x5b, 0x93, 0x65, 0x55, 0x19, 0x4f,
	0x0c, 0x97, 0x43, 0xc5, 0xb3, 0xef, 0xf4, 0xaf, 0x77, 0xb4, 0x9e, 0x83, 0x39, 0xce, 0xe9, 0xc5,
	0x6e, 0x92, 0xc5, 0x1e, 0xcd, 0x62, 0x43, 0x96, 0x5b, 0x2d, 0xc8, 0x1e, 0xd4, 0x8b, 0x0f, 0x23,
	0x7d, 0xb2, 0x69, 0xcf, 0xc0, 0x08, 0xdc, 0xfa, 0xdd, 0x80, 0x3b, 0xaf, 0x48, 0x90, 0xec, 0xc2,
	0xed, 0xc9, 0x53, 0xc7, 0xee, 0x10, 0xf5, 0xe3, 0xb0, 0x36, 0x7e, 0x80, 0xcf, 0xdd, 0x21, 0x92,
	0x17, 0xf0, 0xda, 0x24, 0x8b, 0xeb, 0xfc, 0xf3, 0xf9, 0xb2, 0x3d, 0xb3, 0x5a, 0xf9, 0xc9, 0xed,
	0xf5, 0xfe, 0x2b, 0x3c, 0x7c, 0x7f, 0xfd, 0xfc, 0xa2, 0xb2, 0x90, 0x7d, 0x5d, 0x64, 0x11, 0xce,
	0x2f, 0x2a, 0x75, 0x32, 0xaf, 0xfe, 0xf3, 0xee, 0x83, 0x5f, 0xfe, 0xb9, 0x6b, 0x7c, 0xf3, 0xfa,
	0xb4, 0x2f, 0xd8, 0xe4, 0x24, 0xd0, 0xdf, 0x58, 0xc7, 0x35, 0x29, 0xd6, 0xc3, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0x42, 0x51, 0xdb, 0xaf, 0xf2, 0x0a, 0x00, 0x00,
}

func (this *Experiment) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Experiment)
	if !ok {
		that2, ok := that.(Experiment)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Status.Equal(&that1.Status) {
		return false
	}
	if !this.Spec.Equal(that1.Spec) {
		return false
	}
	if !this.Result.Equal(&that1.Result) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentResult) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentResult)
	if !ok {
		that2, ok := that.(ExperimentResult)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.State != that1.State {
		return false
	}
	if len(this.FailureReport) != len(that1.FailureReport) {
		return false
	}
	for i := range this.FailureReport {
		if this.FailureReport[i] != that1.FailureReport[i] {
			return false
		}
	}
	if !this.TimeStarted.Equal(that1.TimeStarted) {
		return false
	}
	if !this.TimeFinished.Equal(that1.TimeFinished) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentSpec) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentSpec)
	if !ok {
		that2, ok := that.(ExperimentSpec)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Faults) != len(that1.Faults) {
		return false
	}
	for i := range this.Faults {
		if !this.Faults[i].Equal(that1.Faults[i]) {
			return false
		}
	}
	if len(this.FailureConditions) != len(that1.FailureConditions) {
		return false
	}
	for i := range this.FailureConditions {
		if !this.FailureConditions[i].Equal(that1.FailureConditions[i]) {
			return false
		}
	}
	if this.Duration != nil && that1.Duration != nil {
		if *this.Duration != *that1.Duration {
			return false
		}
	} else if this.Duration != nil {
		return false
	} else if that1.Duration != nil {
		return false
	}
	if !this.TargetMesh.Equal(that1.TargetMesh) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *ExperimentSpec_InjectedFault) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ExperimentSpec_InjectedFault)
	if !ok {
		that2, ok := that.(ExperimentSpec_InjectedFault)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.OriginServices) != len(that1.OriginServices) {
		return false
	}
	for i := range this.OriginServices {
		if !this.OriginServices[i].Equal(that1.OriginServices[i]) {
			return false
		}
	}
	if len(this.DestinationServices) != len(that1.DestinationServices) {
		return false
	}
	for i := range this.DestinationServices {
		if !this.DestinationServices[i].Equal(that1.DestinationServices[i]) {
			return false
		}
	}
	if !this.Fault.Equal(that1.Fault) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FailureCondition) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition)
	if !ok {
		that2, ok := that.(FailureCondition)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.FailureTrigger == nil {
		if this.FailureTrigger != nil {
			return false
		}
	} else if this.FailureTrigger == nil {
		return false
	} else if !this.FailureTrigger.Equal(that1.FailureTrigger) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *FailureCondition_WebhookUrl) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_WebhookUrl)
	if !ok {
		that2, ok := that.(FailureCondition_WebhookUrl)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.WebhookUrl != that1.WebhookUrl {
		return false
	}
	return true
}
func (this *FailureCondition_PrometheusTrigger) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*FailureCondition_PrometheusTrigger)
	if !ok {
		that2, ok := that.(FailureCondition_PrometheusTrigger)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.PrometheusTrigger.Equal(that1.PrometheusTrigger) {
		return false
	}
	return true
}
func (this *PrometheusTrigger) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PrometheusTrigger)
	if !ok {
		that2, ok := that.(PrometheusTrigger)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if that1.QueryType == nil {
		if this.QueryType != nil {
			return false
		}
	} else if this.QueryType == nil {
		return false
	} else if !this.QueryType.Equal(that1.QueryType) {
		return false
	}
	if this.ThresholdValue != that1.ThresholdValue {
		return false
	}
	if this.ComparisonOperator != that1.ComparisonOperator {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *PrometheusTrigger_CustomQuery) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PrometheusTrigger_CustomQuery)
	if !ok {
		that2, ok := that.(PrometheusTrigger_CustomQuery)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.CustomQuery != that1.CustomQuery {
		return false
	}
	return true
}
func (this *PrometheusTrigger_SuccessRate) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PrometheusTrigger_SuccessRate)
	if !ok {
		that2, ok := that.(PrometheusTrigger_SuccessRate)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.SuccessRate.Equal(that1.SuccessRate) {
		return false
	}
	return true
}
func (this *PrometheusTrigger_SuccessRateQuery) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*PrometheusTrigger_SuccessRateQuery)
	if !ok {
		that2, ok := that.(PrometheusTrigger_SuccessRateQuery)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Service.Equal(that1.Service) {
		return false
	}
	if this.Interval != nil && that1.Interval != nil {
		if *this.Interval != *that1.Interval {
			return false
		}
	} else if this.Interval != nil {
		return false
	} else if that1.Interval != nil {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Report) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Report)
	if !ok {
		that2, ok := that.(Report)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Metadata.Equal(&that1.Metadata) {
		return false
	}
	if !this.Experiment.Equal(that1.Experiment) {
		return false
	}
	if len(this.FailureConditionHistory) != len(that1.FailureConditionHistory) {
		return false
	}
	for i := range this.FailureConditionHistory {
		if !this.FailureConditionHistory[i].Equal(that1.FailureConditionHistory[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Report_FailureConditionSnapshot) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Report_FailureConditionSnapshot)
	if !ok {
		that2, ok := that.(Report_FailureConditionSnapshot)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Value != that1.Value {
		return false
	}
	if !this.Timestamp.Equal(that1.Timestamp) {
		return false
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
func (this *Report_FailureConditionHistory) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Report_FailureConditionHistory)
	if !ok {
		that2, ok := that.(Report_FailureConditionHistory)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.FailureConditionName != that1.FailureConditionName {
		return false
	}
	if len(this.FailureConditionSnapshots) != len(that1.FailureConditionSnapshots) {
		return false
	}
	for i := range this.FailureConditionSnapshots {
		if !this.FailureConditionSnapshots[i].Equal(that1.FailureConditionSnapshots[i]) {
			return false
		}
	}
	if !bytes.Equal(this.XXX_unrecognized, that1.XXX_unrecognized) {
		return false
	}
	return true
}
