// Code generated by solo-kit. DO NOT EDIT.

package v1

import (
	"github.com/solo-io/go-utils/contextutils"
	"github.com/solo-io/solo-kit/pkg/api/v1/clients"
	"github.com/solo-io/solo-kit/pkg/api/v1/reconcile"
	"github.com/solo-io/solo-kit/pkg/api/v1/resources"
)

// Option to copy anything from the original to the desired before writing. Return value of false means don't update
type TransitionReportFunc func(original, desired *Report) (bool, error)

type ReportReconciler interface {
	Reconcile(namespace string, desiredResources ReportList, transition TransitionReportFunc, opts clients.ListOpts) error
}

func reportsToResources(list ReportList) resources.ResourceList {
	var resourceList resources.ResourceList
	for _, report := range list {
		resourceList = append(resourceList, report)
	}
	return resourceList
}

func NewReportReconciler(client ReportClient) ReportReconciler {
	return &reportReconciler{
		base: reconcile.NewReconciler(client.BaseClient()),
	}
}

type reportReconciler struct {
	base reconcile.Reconciler
}

func (r *reportReconciler) Reconcile(namespace string, desiredResources ReportList, transition TransitionReportFunc, opts clients.ListOpts) error {
	opts = opts.WithDefaults()
	opts.Ctx = contextutils.WithLogger(opts.Ctx, "report_reconciler")
	var transitionResources reconcile.TransitionResourcesFunc
	if transition != nil {
		transitionResources = func(original, desired resources.Resource) (bool, error) {
			return transition(original.(*Report), desired.(*Report))
		}
	}
	return r.base.Reconcile(namespace, reportsToResources(desiredResources), transitionResources, opts)
}
