apiVersion: glooshot.solo.io/v1
kind: Experiment
metadata:
  name: testexperiment3
  namespace: default
spec:
  spec:
    duration: 3600s
    failureConditions:
    - prometheusTrigger:
        customQuery: cpu percent
        thresholdValue: 10
    faults:
    - destinationServices:
      - name: name2
        namespace: default
      fault:
        delay:
          duration: 1s
        percentage: 50
      originServices:
      - name: name1
        namespace: default
    targetMesh:
      name: basicmesh
      namespace: default
