// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/api/v1/report_client.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/solo-io/glooshot/pkg/api/v1"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
)

// MockReportWatcher is a mock of ReportWatcher interface
type MockReportWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockReportWatcherMockRecorder
}

// MockReportWatcherMockRecorder is the mock recorder for MockReportWatcher
type MockReportWatcherMockRecorder struct {
	mock *MockReportWatcher
}

// NewMockReportWatcher creates a new mock instance
func NewMockReportWatcher(ctrl *gomock.Controller) *MockReportWatcher {
	mock := &MockReportWatcher{ctrl: ctrl}
	mock.recorder = &MockReportWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportWatcher) EXPECT() *MockReportWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method
func (m *MockReportWatcher) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.ReportList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.ReportList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockReportWatcherMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockReportWatcher)(nil).Watch), namespace, opts)
}

// MockReportClient is a mock of ReportClient interface
type MockReportClient struct {
	ctrl     *gomock.Controller
	recorder *MockReportClientMockRecorder
}

// MockReportClientMockRecorder is the mock recorder for MockReportClient
type MockReportClientMockRecorder struct {
	mock *MockReportClient
}

// NewMockReportClient creates a new mock instance
func NewMockReportClient(ctrl *gomock.Controller) *MockReportClient {
	mock := &MockReportClient{ctrl: ctrl}
	mock.recorder = &MockReportClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportClient) EXPECT() *MockReportClientMockRecorder {
	return m.recorder
}

// BaseClient mocks base method
func (m *MockReportClient) BaseClient() clients.ResourceClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BaseClient")
	ret0, _ := ret[0].(clients.ResourceClient)
	return ret0
}

// BaseClient indicates an expected call of BaseClient
func (mr *MockReportClientMockRecorder) BaseClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BaseClient", reflect.TypeOf((*MockReportClient)(nil).BaseClient))
}

// Register mocks base method
func (m *MockReportClient) Register() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register")
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register
func (mr *MockReportClientMockRecorder) Register() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockReportClient)(nil).Register))
}

// Read mocks base method
func (m *MockReportClient) Read(namespace, name string, opts clients.ReadOpts) (*v1.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read", namespace, name, opts)
	ret0, _ := ret[0].(*v1.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read
func (mr *MockReportClientMockRecorder) Read(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockReportClient)(nil).Read), namespace, name, opts)
}

// Write mocks base method
func (m *MockReportClient) Write(resource *v1.Report, opts clients.WriteOpts) (*v1.Report, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", resource, opts)
	ret0, _ := ret[0].(*v1.Report)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write
func (mr *MockReportClientMockRecorder) Write(resource, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockReportClient)(nil).Write), resource, opts)
}

// Delete mocks base method
func (m *MockReportClient) Delete(namespace, name string, opts clients.DeleteOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", namespace, name, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockReportClientMockRecorder) Delete(namespace, name, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockReportClient)(nil).Delete), namespace, name, opts)
}

// List mocks base method
func (m *MockReportClient) List(namespace string, opts clients.ListOpts) (v1.ReportList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", namespace, opts)
	ret0, _ := ret[0].(v1.ReportList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List
func (mr *MockReportClientMockRecorder) List(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockReportClient)(nil).List), namespace, opts)
}

// Watch mocks base method
func (m *MockReportClient) Watch(namespace string, opts clients.WatchOpts) (<-chan v1.ReportList, <-chan error, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", namespace, opts)
	ret0, _ := ret[0].(<-chan v1.ReportList)
	ret1, _ := ret[1].(<-chan error)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Watch indicates an expected call of Watch
func (mr *MockReportClientMockRecorder) Watch(namespace, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockReportClient)(nil).Watch), namespace, opts)
}
