// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/api/v1/report_reconciler.sk.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	v1 "github.com/solo-io/glooshot/pkg/api/v1"
	clients "github.com/solo-io/solo-kit/pkg/api/v1/clients"
)

// MockReportReconciler is a mock of ReportReconciler interface
type MockReportReconciler struct {
	ctrl     *gomock.Controller
	recorder *MockReportReconcilerMockRecorder
}

// MockReportReconcilerMockRecorder is the mock recorder for MockReportReconciler
type MockReportReconcilerMockRecorder struct {
	mock *MockReportReconciler
}

// NewMockReportReconciler creates a new mock instance
func NewMockReportReconciler(ctrl *gomock.Controller) *MockReportReconciler {
	mock := &MockReportReconciler{ctrl: ctrl}
	mock.recorder = &MockReportReconcilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockReportReconciler) EXPECT() *MockReportReconcilerMockRecorder {
	return m.recorder
}

// Reconcile mocks base method
func (m *MockReportReconciler) Reconcile(namespace string, desiredResources v1.ReportList, transition v1.TransitionReportFunc, opts clients.ListOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconcile", namespace, desiredResources, transition, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconcile indicates an expected call of Reconcile
func (mr *MockReportReconcilerMockRecorder) Reconcile(namespace, desiredResources, transition, opts interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconcile", reflect.TypeOf((*MockReportReconciler)(nil).Reconcile), namespace, desiredResources, transition, opts)
}
